import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
const base=process.env.JOURNAL_TEST_URL??'http://127.0.0.1:4321';
const browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHANNEL?{channel:process.env.PLAYWRIGHT_CHANNEL}:{})});
await mkdir('.workspace/journal-checks',{recursive:true});
const context=await browser.newContext({viewport:{width:918,height:970}});
const page=await context.newPage(),errors=[];
page.on('pageerror',e=>errors.push(e.message));
const canvas=page.locator('canvas[data-journal-phase]');
const phase=value=>page.waitForFunction(value=>document.querySelector('canvas[data-journal-phase]')?.dataset.journalPhase===value,value);
const shot=name=>page.screenshot({path:'.workspace/journal-checks/'+name+'.png'});
const drag=async(x,y,dx,dy)=>{await page.mouse.move(x,y);await page.mouse.down();await page.mouse.move(x+dx,y+dy,{steps:15});await page.mouse.up();};
try{
  const manifest=await (await page.request.get(base+'/journal/generated/manifest.json')).json();
  const count=manifest.pages.length,slug=encodeURIComponent(manifest.articles[0].slug);
  await page.goto(base+'/journal');await phase('observing');
  await page.waitForFunction(()=>!document.querySelector('[data-journal-root]').classList.contains('is-entering'));
  await shot('inspection-cover');
  assert.equal(await page.locator('[data-journal-text]').isVisible(),false);
  await drag(450,400,445,0);
  assert.equal(await canvas.getAttribute('data-journal-phase'),'observing','rotation must not activate the cover');
  assert.ok(Number(await canvas.getAttribute('data-journal-yaw'))>2.5);
  await shot('inspection-back');
  await page.locator('[data-journal-reset]').click();
  assert.equal(await canvas.getAttribute('data-journal-yaw'),'0');
  await page.mouse.click(450,400);await phase('reading');
  await shot('inspection-reading');
  assert.equal(await page.locator('[data-journal-progress]').textContent(),'1–2 / '+count);
  await drag(550,400,340,300);
  assert.ok(Math.abs(Number(await canvas.getAttribute('data-journal-yaw')))<=25*Math.PI/180);
  assert.ok(Math.abs(Number(await canvas.getAttribute('data-journal-pitch')))<=15*Math.PI/180);
  assert.equal(await canvas.getAttribute('data-journal-page'),'0','body drag must not turn a page');
  await page.locator('[data-journal-reset]').click();
  await page.getByRole('button',{name:'拉近书本',exact:true}).click();
  assert.equal(await canvas.getAttribute('data-journal-zoom'),'1.25');
  assert.equal(await page.locator('[data-journal-image]').isVisible(),false);
  await drag(550,400,50,20);assert.notEqual(await canvas.getAttribute('data-journal-pan'),'0,0');await page.locator('[data-journal-reset]').click();
  assert.equal(await canvas.getAttribute('data-journal-pan'),'0,0');
  await page.mouse.move(450,400);await page.mouse.wheel(0,-200);
  await page.waitForFunction(()=>Number(document.querySelector('canvas[data-journal-zoom]').dataset.journalZoom)>1);
  await page.locator('[data-journal-reset]').click();
  await page.locator('[data-journal-mode]').click();
  assert.match(await page.locator('[data-journal-text]').textContent(),/生活节奏/);
  await page.keyboard.press('Escape');assert.equal(await page.locator('[data-journal-text]').isVisible(),false);
  assert.equal(await page.locator('[data-journal-directory]').count(),0);
  await page.setViewportSize({width:390,height:844});
  await page.waitForFunction(()=>document.querySelector('[data-journal-progress]').textContent.startsWith('1 /'));
  await shot('inspection-mobile');
  const touch=await context.newCDPSession(page);
  await touch.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:160,y:350,id:1},{x:220,y:380,id:2}]});
  await touch.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:110,y:340,id:1},{x:280,y:390,id:2}]});
  await touch.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
  await page.waitForFunction(()=>Number(document.querySelector('canvas[data-journal-zoom]').dataset.journalZoom)>1);
  await page.locator('[data-journal-reset]').click();await touch.detach();
  await page.keyboard.press('ArrowRight');
  await page.waitForTimeout(280);await shot('inspection-turn');
  await page.waitForFunction(()=>document.querySelector('canvas[data-journal-page]').dataset.journalPage==='1'&&document.querySelector('canvas[data-journal-busy]').dataset.journalBusy==='false');
  await page.setViewportSize({width:844,height:390});
  assert.equal(await canvas.getAttribute('data-journal-page'),'1');
  await page.setViewportSize({width:1440,height:1000});await shot('inspection-wide');
  await page.keyboard.press('Escape');await phase('observing');
  await page.keyboard.press('Escape');await page.waitForURL('**/home');
  await page.waitForFunction(()=>document.querySelector('[data-studio]').dataset.state==='room');
  assert.equal(await canvas.getAttribute('data-journal-textures'),'0');
  await page.locator('[data-studio-explore]').focus();await page.locator('[data-studio-explore]').click();await page.locator('[data-studio-action="diary"]').click();
  await page.waitForURL('**/journal');await phase('observing');
  await page.goBack();await page.waitForURL('**/home');await page.goForward();await page.waitForURL('**/journal');await phase('observing');
  await page.goto(base+'/journal/'+slug);
  await page.waitForURL('**/journal/'+slug);await phase('reading');
  await page.reload();await phase('reading');assert.match(await page.title(),/记录和节奏/);
  assert.equal((await page.request.get(base+'/blog/'+slug,{maxRedirects:0})).status(),301);
  assert.match(await (await page.request.get(base+'/rss.xml')).text(),/记录和节奏/);
  assert.equal((await page.request.get(base+'/api/health')).status(),200);
  assert.deepEqual(errors,[]);
  console.log('Journal inspection passed: front/back, cover activation, rotation limits, reading layout, zoom/pan, keyboard, mobile/rotation, history, article routes, RSS and health.');
}finally{await browser.close();}
